# DreamBooth LoRA Training Configuration

# Model Configuration
pretrained_model_name_or_path: "sd1-4"  # Required
revision: null
tokenizer_name: null

# Data Configuration
instance_data_dir: "./dataset/dog"  # Required - path to instance images
class_data_dir: "./dataset/class_img_cache"
instance_prompt: "a photo of sks dog"  # Required - prompt with identifier
class_prompt: "a photo of dog"

# Prior Preservation
with_prior_preservation: true
prior_loss_weight: 1.0
num_class_images: 200

# Validation
validation_prompt: null
num_validation_images: 4
validation_steps: 100

# Output Configuration
output_dir: "outputs/dreambooth-lora-model-dog"
seed: null
resolution: 512
center_crop: false

# LoRA Configuration
use_lora: true
lora_r: 16
lora_alpha: 27
lora_dropout: 0.0
lora_bias: "none"

# Text Encoder Training
train_text_encoder: true
lora_text_encoder_r: 16
lora_text_encoder_alpha: 17
lora_text_encoder_dropout: 0.0
lora_text_encoder_bias: "none"

# Training Configuration
train_batch_size: 1
sample_batch_size: 4
num_train_epochs: 1
max_train_steps: 800
checkpointing_steps: 500
resume_from_checkpoint: null
gradient_accumulation_steps: 1
gradient_checkpointing: true
num_dataloader_workers: 1
no_tracemalloc: false

# Optimization
learning_rate: 0.0001
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 0
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 0.00000001
max_grad_norm: 1.0

# Hub Configuration
push_to_hub: false
hub_token: null
hub_model_id: null

# Logging
logging_dir: "logs"
report_to: "tensorboard"
wandb_key: null
wandb_project_name: null

# Hardware Configuration
allow_tf32: false
mixed_precision: null  # "no", "fp16", "bf16"
prior_generation_precision: null  # "fp32", "fp16", "bf16"
local_rank: -1
enable_xformers_memory_efficient_attention: false

# Inference Configuration (for inference.py)
inference:
  prompts:
    - "A photo of sks dog"
    - "A photo of sks dog in a garden"
    - "A photo of sks dog playing"
    - "A portrait of sks dog"
  negative_prompt: ""
  num_inference_steps: 50
  guidance_scale: 7
  num_images_per_prompt: 1
  height: 512
  width: 512
  generator_seed: 42
  output_dir: "inference_results/"
  compare_with_base_model: true