# DreamBooth Official Configuration (without LoRA)
# Based on the original DreamBooth paper parameters

# Model Configuration
pretrained_model_name_or_path: "sd1-4"  # Required
revision: null
tokenizer_name: null

# Data Configuration
instance_data_dir: "./dataset/dog"  # Required - path to instance images
class_data_dir: "./dataset/class_img_cache"
instance_prompt: "a photo of sks dog"  # Required - prompt with identifier
class_prompt: "a photo of dog"

# Prior Preservation (Essential for DreamBooth)
with_prior_preservation: true
prior_loss_weight: 1.0  # Î» = 1 as mentioned in paper
num_class_images: 1000  # Paper mentions ~1000 samples

# Validation
validation_prompt: null
num_validation_images: 4
validation_steps: 100

# Output Configuration
output_dir: "outputs/dreambooth-official-model-dog"
seed: null
resolution: 512
center_crop: false

# LoRA Configuration (Disabled for official DreamBooth)
use_lora: false
lora_r: null
lora_alpha: null
lora_dropout: null
lora_bias: null

# Text Encoder Training (Disabled for official DreamBooth)
train_text_encoder: false
lora_text_encoder_r: null
lora_text_encoder_alpha: null
lora_text_encoder_dropout: null
lora_text_encoder_bias: null

# Training Configuration (Official DreamBooth parameters)
train_batch_size: 1
sample_batch_size: 4
num_train_epochs: null  # Use max_train_steps instead
max_train_steps: 1000  # Paper suggests ~1000 iterations
checkpointing_steps: 500
resume_from_checkpoint: null
gradient_accumulation_steps: 1
gradient_checkpointing: true
num_dataloader_workers: 1
no_tracemalloc: false

# Optimization (Official DreamBooth parameters)
learning_rate: 0.000005  # 5e-6 for Stable Diffusion as per paper
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 0
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 0.00000001
max_grad_norm: 1.0

# Hub Configuration
push_to_hub: false
hub_token: null
hub_model_id: null

# Logging
logging_dir: "logs"
report_to: "tensorboard"
wandb_key: null
wandb_project_name: null

# Hardware Configuration
allow_tf32: false
mixed_precision: null  # "no", "fp16", "bf16"
prior_generation_precision: null  # "fp32", "fp16", "bf16"
local_rank: -1
enable_xformers_memory_efficient_attention: false

# Inference Configuration
inference:
  prompts:
    - "A photo of sks dog"
    - "A photo of sks dog in a garden"
    - "A photo of sks dog playing"
    - "A portrait of sks dog"
  negative_prompt: ""
  num_inference_steps: 50
  guidance_scale: 7
  num_images_per_prompt: 1
  height: 512
  width: 512
  generator_seed: 42
  output_dir: "inference_results/"
  compare_with_base_model: true